# This script categorises endemism among the species in the lists generated by
# 2_species_richness.R.
#
# For vertebrates, occurrences are first generalised to a 10 by 10 km grid and
# endemism is calculated as a proportion of occupied grid cells rather than a
# proportion of records (mitigates somewhat issues around sampling inconsistency)
#
# For plants, endemism is calculated based on the proportion of occurrence
# records occurring within the hotspot relative to the total number of
# occurrences across Australia. 
# 
# NOTE: if re-writing scripts, parquet files would be faster to write (but
# bigger) so might be worth swapping over from RDS files
#
# TODO: 
# figure out why length(all_occ) is != nrow(vertebrate_taxa)
# maybe add some checks for endemic species?

# vertebrates ------

### spatial wrangling ----
albers_crs = 3577
grid_size = 10000
hotspot_sf <- readRDS(here("data", "processed", "hotspot_sf.RDS"))
tropics_sf <- readRDS(here("data", "processed", "tropics_sf.RDS"))
temperate_sf <- readRDS(here("data", "processed", "temperate_sf.RDS"))

# grid across terrestrial aus
aus_map <- st_transform(ozmap_country, crs = albers_crs)

aus_grid <- st_make_grid(aus_map, 
                         cellsize = c(grid_size, grid_size),
                         square = TRUE) |> 
  st_intersection(st_geometry(aus_map)) |>  
  st_as_sf() |> 
  st_set_geometry("grid_geometry") |> 
  tibble::rowid_to_column(var = "grid_id")

### get occurrence records ------
dir.create("data/tmp_occ")

# keep this as a reference for joining later 
vertebrate_taxa <- reclassify_groups("vertebrates_hotspot.RDS") |> 
  list_rbind(names_to = "ala_classification") |> 
  select(ala_classification, taxon_concept_id)

vertebrate_taxa |> 
  pull(taxon_concept_id) |> 
  map(save_occ)

all_occ <- list.files("data/tmp_occ", full.names = TRUE)

### hotspot ----
all_occ |> 
  map(get_grid_counts, region_sf = hotspot_sf) |> 
  bind_rows() |> 
  saveRDS(here("data", "processed", "vertebrates_hotspot_counts.RDS"))

get_endemic_spp("vertebrates_hotspot_counts.RDS")

### ecoregions ------
#tropics
tropics_spp <- readRDS(here("data", "processed", "vertebrates_tropics.RDS")) |> 
  map(select, species_name) |> 
  list_rbind() |> 
  mutate(species_name = str_remove_all(species_name, "\\s*\\([^)]*\\)")) |> 
  tibble::rowid_to_column("tropics_id")
  
all_occ |> 
  as_tibble() |> 
  mutate(species_name = str_extract(value, "(?<=occ/).*?(?=\\.RDS)")) |> 
  full_join(tropics_spp, by = "species_name") |> 
  filter(!is.na(tropics_id)) |> 
  pull(value) |> 
  map(get_grid_counts, region_sf = tropics_sf) |> 
  bind_rows() |> 
  saveRDS(here("data", "processed", "vertebrates_tropics_counts.RDS"))

get_endemic_spp("vertebrates_tropics_counts.RDS")

# temperate
temperate_spp <- readRDS(here("data", "processed", "vertebrates_temperate.RDS")) |> 
  map(select, species_name) |> 
  list_rbind() |> 
  mutate(species_name = str_remove_all(species_name, "\\s*\\([^)]*\\)")) |> 
  tibble::rowid_to_column("temperate_id")

all_occ |> 
  as_tibble() |> 
  mutate(species_name = str_extract(value, "(?<=occ/).*?(?=\\.RDS)")) |> 
  full_join(temperate_spp, by = "species_name") |> 
  filter(!is.na(temperate_id)) |> 
  pull(value) |> 
  map(get_grid_counts, region_sf = temperate_sf) |> 
  bind_rows() |> 
  saveRDS(here("data", "processed", "vertebrates_temperate_counts.RDS"))

get_endemic_spp("vertebrates_temperate_counts.RDS")


# vascular plants ------
### hotspot -----
reclassify_groups("vascular_plants_hotspot.RDS") |> 
  map(~ .x |>
        mutate(
          aus_count = unlist(pmap(list(.x$taxon_concept_id), 
                                  get_aus_counts)),
          region_count = unlist(pmap(list(.x$taxon_concept_id), 
                                     get_region_counts, 
                                     region_type = hotspot_regions)),
          prop_within_region = round(region_count/aus_count, 3),
          endemic = case_when(
            between(region_count, 10, 50) & prop_within_region == 1.00 ~ "endemic",
            region_count > 50 & prop_within_region >= 0.950 ~ "endemic"))) |>
  saveRDS(here("data", "processed", "vascular_plants_hotspot_endemic.RDS"))

### ecoregions -----
# tropics
reclassify_groups("vascular_plants_tropics.RDS") |> 
  map(~ .x |>
        mutate(
          aus_count = unlist(pmap(list(.x$taxon_concept_id), 
                                  get_aus_counts)),
          region_count = unlist(pmap(list(.x$taxon_concept_id), 
                                     get_region_counts, 
                                     region_type = tropics_regions)),
          prop_within_region = round(region_count/aus_count, 3),
          endemic = case_when(
            between(region_count, 10, 50) & prop_within_region == 1.00 ~ "endemic",
            region_count > 50 & prop_within_region >= 0.950 ~ "endemic"))) |> 
  saveRDS(here("data", "processed", "vascular_plants_tropics_endemic.RDS"))

# temperate
reclassify_groups("vascular_plants_temperate.RDS") |> 
  map(~ .x |>
        mutate(
          aus_count = unlist(pmap(list(.x$taxon_concept_id), 
                                  get_aus_counts)),
          region_count = unlist(pmap(list(.x$taxon_concept_id), 
                                     get_region_counts, 
                                     region_type = temperate_regions)),
          prop_within_region = round(region_count/aus_count, 3),
          endemic = case_when(
            between(region_count, 10, 50) & prop_within_region == 1.00 ~ "endemic",
            region_count > 50 & prop_within_region >= 0.950 ~ "endemic"))) |> 
  saveRDS(here("data", "processed", "vascular_plants_temperate_endemic.RDS"))
