# This script gets habitat data for fish species of interest. Species names are
# first matched to those in FishBase using the rfishbase package. Species
# without a corresponding match to the taxonomy of FishBase are run through
# validate_names() to look for matches in the list of synonyms in FishBase.
# Those not matched using either of those methods are then manually checked
# using the search function on the FishBase website, and the best match chosen
# by comparing descriptions on FishBase and the Australian Faunal Directory.
#
# For species matched using any of the above three methods, habitat data is then
# derived from FishBase using the rfishbase package. Marine species are those
# that are found wholly in marine habitats, and freshwater species are those
# found in any combination of marine, freshwater, or brackish habitats.
#
# For species not matched using the three methods described above, habitat data
# was determined by checking descriptions in the Australian Faunal Directory.
#
# data/tmp_fish/readme.txt describes the files generated by this script. 


# match taxonomy and get species codes -------
fish <- load_taxa()
saveRDS(fish, "data/tmp_fish/fish_ds.RDS")

ala_fish <- reclassify_groups("vertebrates_hotspot.RDS") |> 
  pluck("fish") |> 
  ungroup()

joined_fish <- ala_fish |> 
  select(taxon_concept_id, species_name) |> 
  left_join(fish, by = join_by(species_name == Species))

### 1. perfect match ------
# names in ALA match names in FishBase 
# 1682 / 1784 species
perfect_match <- joined_fish |> 
  filter(!is.na(SpecCode),
         SpecCode != 0) |> 
  select(species_name, SpecCode) |> 
  mutate(source = "perfect match")

### 2. validated match -------
# names in ALA and FishBase do not match, but ALA names are found in list of 
# synonyms in FishBase
# 82 / 1784 species
unmatched_fish <- joined_fish |>
  filter(is.na(SpecCode) | SpecCode == 0) 
 
validated_names <- validate_names(unmatched_fish$species_name)
 
validated_joined <- validated_names |>
  as_tibble_col(column_name = "validated_names") |> 
  bind_cols(unmatched_fish$species_name) |> 
  rename("species_name" = "...2") |> 
  left_join(fish, by = join_by(validated_names == Species)) 
 
validated_match <- validated_joined |> 
  filter(!is.na(SpecCode),
         SpecCode != 0) |> 
  select(species_name, SpecCode) |> 
  mutate(source = "validated match")
 
### 3. no match, no validation ------
# manually check names on FishBase website (https://www.fishbase.se/search.php) 
# and find best match based on details in AFD record (via taxon concept ID)
# rfishbase accesses static snapshots of the raw database tables used by the
# website, so can sometimes be less complete than the latest information
# available online
# 15 / 1784 species

no_match_fish <- validated_joined |> 
  filter(is.na(SpecCode)) |> 
  pull(species_name)
 
ala_fish |> 
  filter(species_name %in% no_match_fish) |> 
  select(species_name_ala = species_name, taxon_concept_id) |> 
  write_csv("data/tmp_fish/check_names_website.csv")

manual_match <- read_csv("data/tmp_fish/matched_on_website.csv") |> 
  left_join(fish, by = join_by(species_name_fishbase == Species)) |> 
  select(species_name = species_name_ala, SpecCode) |> 
  mutate(source = "fishbase website")

### 4. not in FishBase ------
# get habitat by looking up species elsewhere 
# 3 species with SpecCode == 0 from validated_joined and 2 species not found on 
# the FishBase website
# 5 / 1784 species

unmatched_anywhere <- read_csv("data/tmp_fish/unmatched_anywhere.csv") 
  
# get habitats ------
fb <- fb_tbl("species")
saveRDS(fb, "data/tmp_fish/species_ds.RDS")

somewhat_matched_fish <- bind_rows(perfect_match, 
                                   validated_match, 
                                   manual_match)

matched_habitat <- somewhat_matched_fish |> 
  left_join(fb, by = "SpecCode") |> 
  select(SpecCode, species_name, Fresh, Brack, Saltwater, source) |> 
  clean_names() |> 
  bind_rows(unmatched_anywhere) |> 
  select(-c(taxon_concept_id, spec_code)) |> 
  mutate(habitat_type = case_when(
    saltwater == 1 & fresh == 0 & brack == 0 ~ "marine",
    saltwater == 0 & fresh == 0 & brack == 0 ~ "check values",
    .default = "freshwater"
  ))

# should be TRUE
nrow(filter(matched_habitat, habitat_type == "check values")) == 0

saveRDS(matched_habitat, "data/processed/fish_habitats.RDS")
